baseURL = ""
languageCode = "en-us"
title = "Seekintoo Ltd. Site Title"
paginate = 6

[taxonomies]
  categories = "categories"
  
[params]
description = "Anim aute id magna aliqua adadnon polonem asum nuerom deserunt sunt."
logo = "/images/logo.png"
logo_light = "/images/logo-light.png"
copyright = "Copyright © 2022 Seekintoo"

[params.gated]
  heading = "Get the Xyz content"
  subheading ="Anim aute id magna aliqua adadnon polonem dolorem ipsumer amorom deole asum nuerom deserunt sunt."

# banner_text = "Excepteur sint occaecat cupidatat proident officia deserunt"
# banner_url = "#"