baseURL = ""
languageCode = "en-us"
title = "Seekintoo Ltd. Site Title"
paginate = 6

[taxonomies]
  categories = "categories"
  
[params]
description = "Trusted cybersecurity services since 2012"
logo = "/images/logo.png"
logo_light = "/images/logo-light.png"
copyright = "Copyright © 2022 Seekintoo"
banner_text = "Banner"
banner_url = "#"

[params.gated]
  heading = "Get the Xyz content"
  subheading ="Anim aute id magna aliqua adadnon polonem dolorem ipsumer amorom deole asum nuerom deserunt sunt."


[outputFormats.search]
baseName = "search"
isPlainText = true
mediaType = "application/json"
[outputs]
home = ["HTML", "RSS", "search"]